disks:
    - partitions:
        - size: 2MB
          filesystem: ext2
          contentpath: ./boot
          userid:
          groupid:
          boot: True
        - size: 10MB
          boot: False
